// Problem::Given two strings s and t which consist of only lowercase letters.
            //
            // String t is generated by random shuffling string s and then add one more letter at a random position.
            //
            // Find the letter that was added in t.
            //
            // Example:
            //
            // Input:
            // s = "abcd"
            // t = "abcde"
            //
            // Output:
            // e
            //
            // Explanation:
            // 'e' is the letter that was added.

#include<bits/stdc++.h>
using namespace std;

char findTheDifference(string s, string t) {

        unordered_map<char,int> map(s.size());

        for(int i=0;i<s.size();i++)
        {
            if(map[s[i]] <0)
                map[s[i]]=0;
            else
                map[s[i]]++;
        }

        for(int i=0;i<map.size();i++)
            cout<<map[i]<<endl;

        for(int i=0;i<t.size();i++)
        {
            if(map[t[i]]<=0)
                return t[i];
            else
                map[t[i]]--;
        }

        return 'x';

}

int main()
{
    string s,t;
    cout<<"Enter string s:";
    cin>>s;
    cout<<"Enter string t:";
    cin>>t;

    cout<<"Difference is:"<<findTheDifference(s,t)<<endl;
    return 0;
}
